### PR TITLE
feature: create README.md

### PR DESCRIPTION
**Pull request by lucasreta**
add a link to the blog post with the explanation of this implementation.

### CODE REVIEW

**Review by vassalloandrea — APPROVED** [review]
Cool thanks! 🚀

**Comment by lucasreta** [comment]
thank you for the repo and post, nice and simple explanation on how to tie these two libraries together!

**Comment by lucasreta** [comment]
I'd merge this but have no write access @vassalloandrea

**Comment by vassalloandrea** [comment]
> I'd merge this but have no write access @vassalloandrea

Done 😃 thank you

**Pull request merged**
